services:
  jupyter-notebook:
    image: abeba/p2p_loan_risk-analysis:4e81403
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64