name: loan_risk522
channels:
  - conda-forge
dependencies:
  -  python=3.11.6
  -  numpy=1.24.4
  -  pandas=2.2.2
  -  scikit-learn=1.5.2
  -  altair=5.1.0
  -  matplotlib=3.9.2
  -  vegafusion-python-embed=1.6.9
  -  vegafusion=1.6.9
  -  vl-convert-python=1.6.0
  -  ipykernel=6.29.5
  -  pandera=0.20.4

  


